# Generated by Django 4.2.4 on 2023-08-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contract_date', models.DateField()),
                ('urls', models.URLField()),
                ('contract_admin', models.CharField(max_length=200)),
            ],
        ),
    ]
